export const cy = {
  app: "app-shell",
  navigation: "main-navigation",
  dashboard: "contest-dashboard",
  analyzeNotice: "analyze-notice",
  courses: "courses-catalog",
  aiToggle: "ai-assistant-toggle",
  aiPanel: "ai-assistant-panel",
  aiInput: "ai-assistant-input",
  aiSend: "ai-assistant-send",
  courseCard: "course-santo-andre",
  openCourse: "open-course-santo-andre",
  studyPath: "study-path",
  lesson: "lesson-cariology",
  lessonVideo: "lesson-video",
  lessonTabs: "lesson-tabs",
  lessonTab: "lesson-tab",
  lessonPdf: "lesson-pdf",
  notebookPrompt: "notebooklm-prompt",
  copyNotebookPrompt: "copy-notebooklm-prompt",
  practiceQuestion: "practice-question",
  practiceAnswer: "practice-answer-a",
  audioReview: "audio-review",
} as const;
