"use client";

import { useMemo, useState } from "react";

const steps = ["Concurso", "Matérias", "Módulos e aulas", "Materiais", "Questões e prompts", "Revisão"];
type Subject = { title: string; hours: string; priority: string };

export function ManualCourseAuthoring() {
  const [open, setOpen] = useState(false);
  const [step, setStep] = useState(0);
  const [title, setTitle] = useState("");
  const [position, setPosition] = useState("");
  const [organization, setOrganization] = useState("");
  const [city, setCity] = useState("");
  const [stateCode, setStateCode] = useState("SP");
  const [subjects, setSubjects] = useState<Subject[]>([{ title: "", hours: "", priority: "3" }]);
  const [videoUrl, setVideoUrl] = useState("");
  const [notice, setNotice] = useState<string | null>(null);
  const [noticeId, setNoticeId] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [lessonId, setLessonId] = useState<string | null>(null);
  const [questionPrompt, setQuestionPrompt] = useState("");
  const [questionExplanation, setQuestionExplanation] = useState("");
  const [summary, setSummary] = useState("");
  const [notebookPrompt, setNotebookPrompt] = useState("");
  const [audioScript, setAudioScript] = useState("");
  const [options, setOptions] = useState(["", ""]);
  const canAdvance = step !== 0 || Boolean(title.trim() && position.trim() && organization.trim() && city.trim() && stateCode.trim());
  const videoId = useMemo(() => { try { const url = new URL(videoUrl); return url.searchParams.get("v") ?? (url.hostname.includes("youtu.be") ? url.pathname.slice(1) : null); } catch { return null; } }, [videoUrl]);
  async function request(path: string, body?: unknown, method = "POST") { const response = await fetch(path, { method: body ? method : "GET", headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const payload = await response.json() as Record<string, unknown>; if (!response.ok) throw new Error(String(payload.error ?? "Não foi possível salvar.")); return payload; }
  async function advance() {
    if (!canAdvance || saving) return; setSaving(true); setNotice(null);
    try {
      if (step === 0 && !noticeId) { const result = await request("/api/manual/concursos", { title, positionTitle: position, organizationName: organization, city, stateCode }); setNoticeId(String((result.notice as { id: string }).id)); }
      if (step === 1 && noticeId) for (const subject of subjects.filter((item) => item.title.trim())) await request(`/api/manual/concursos/${noticeId}/materias`, { title: subject.title, estimatedHours: subject.hours ? Number(subject.hours) : null, priority: Number(subject.priority) });
      if (step === 2 && noticeId) { const result = await request(`/api/manual/concursos/${noticeId}/trilha`, {}); const course = result.course as { learning_modules?: { learning_lessons?: { id: string }[] }[] }; const firstLesson = course.learning_modules?.flatMap((module) => module.learning_lessons ?? [])[0]; setLessonId(firstLesson?.id ?? null); setNotice(`Trilha criada com ${course.learning_modules?.length ?? 0} módulo(s).`); }
      if (step === 3 && lessonId) { await request(`/api/manual/aulas/${lessonId}`, { summary, notebookPrompt, audioScript, authoringStatus: "in_review" }, "PATCH"); if (videoUrl) await request(`/api/manual/aulas/${lessonId}/ativos`, { assetKind: "video", title: "Vídeo complementar", url: videoUrl, sourceLabel: "YouTube", sourceUrl: videoUrl, status: "planned" }); }
      if (step === 4 && lessonId && questionPrompt.trim() && questionExplanation.trim() && options.every((item) => item.trim())) await request(`/api/manual/aulas/${lessonId}/questoes`, { prompt: questionPrompt, options, correctOptionIndex: 0, explanation: questionExplanation, sourceReferences: [] });
      if (step === 5 && noticeId) { const result = await request(`/api/manual/concursos/${noticeId}/pronto`, {}); setNotice(result.ready ? "Trilha privada liberada para estudo." : `Faltam: ${((result.missing as string[]) ?? []).join(", ")}.`); return; }
      setStep((current) => Math.min(steps.length - 1, current + 1));
    } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível salvar."); } finally { setSaving(false); }
  }
  if (!open) return <section className="manual-authoring-callout" data-cy="manual-course-entry"><div><span className="tag">TRILHA PARTICULAR</span><h2>Vai prestar outro concurso?</h2><p>Crie uma trilha manual e mantenha o conteúdo privado, separado dos editais verificados.</p></div><button className="primario" type="button" onClick={() => setOpen(true)} data-cy="manual-course-create">Criar concurso manual</button></section>;
  return <section className="manual-authoring" data-cy="manual-course-authoring"><header><div><span className="tag">ASSISTENTE DE AUTORIA</span><h2>Nova trilha manual</h2><p>O conteúdo permanece privado e não altera o catálogo de editais.</p></div><button type="button" className="secundario" onClick={() => setOpen(false)}>Fechar</button></header><ol className="manual-steps" aria-label="Etapas de criação">{steps.map((label, index) => <li className={index === step ? "active" : index < step ? "done" : ""} key={label}><button type="button" onClick={() => setStep(index)} aria-current={index === step ? "step" : undefined}>{index + 1}. {label}</button></li>)}</ol>
    {step === 0 && <div className="manual-form"><label>Título do concurso<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Ex.: Prefeitura de Campinas 2027" data-cy="manual-notice-title" /></label><label>Cargo<input value={position} onChange={(event) => setPosition(event.target.value)} placeholder="Ex.: Cirurgião-dentista" /></label><label>Órgão ou banca<input value={organization} onChange={(event) => setOrganization(event.target.value)} placeholder="Ex.: Prefeitura de Campinas" /></label><div className="manual-row"><label>Cidade<input value={city} onChange={(event) => setCity(event.target.value)} /></label><label>UF<input value={stateCode} maxLength={2} onChange={(event) => setStateCode(event.target.value.toUpperCase())} /></label></div><label>URL pública do edital, opcional<input type="url" placeholder="https://..." /></label></div>}
    {step === 1 && <div className="manual-form"><p>Inclua as matérias e o esforço estimado. Cada uma dará origem a um módulo privado.</p>{subjects.map((subject, index) => <div className="manual-subject" key={index}><label>Matéria<input value={subject.title} onChange={(event) => setSubjects((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, title: event.target.value } : item))} placeholder="Ex.: Saúde coletiva" /></label><label>Horas<input type="number" min="1" value={subject.hours} onChange={(event) => setSubjects((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, hours: event.target.value } : item))} /></label><label>Prioridade<select value={subject.priority} onChange={(event) => setSubjects((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, priority: event.target.value } : item))}><option value="1">1, baixa</option><option value="3">3, média</option><option value="5">5, alta</option></select></label></div>)}<button type="button" className="secundario" onClick={() => setSubjects((items) => [...items, { title: "", hours: "", priority: "3" }])}>Adicionar matéria</button></div>}
    {step === 2 && <div className="manual-preview"><h3>Módulos e aulas</h3><p>Ao salvar as matérias, cada módulo começa com uma aula editável. Você poderá dividir uma matéria em subtópicos sem alterar o edital oficial.</p><ul>{subjects.filter((subject) => subject.title).map((subject) => <li key={subject.title}><b>{subject.title}</b><span>Aula inicial, objetivo e tempo configuráveis</span></li>)}</ul></div>}
    {step === 3 && <div className="manual-form"><h3>Materiais da aula</h3><p>Vídeos usam somente o player oficial do YouTube. PDF e áudio particulares serão ligados ao armazenamento privado quando o envio estiver disponível.</p><label>Resumo da aula<textarea value={summary} onChange={(event) => setSummary(event.target.value)} placeholder="Resumo que o aluno verá" /></label><label>URL do YouTube<input value={videoUrl} onChange={(event) => setVideoUrl(event.target.value)} placeholder="https://www.youtube.com/watch?v=..." data-cy="manual-youtube-url" /></label>{videoId ? <div className="manual-video-preview"><iframe src={`https://www.youtube-nocookie.com/embed/${videoId}?rel=0`} title="Prévia do vídeo informado" /><p>Prévia pelo player oficial. Sempre inclua atribuição e link de origem na liberação.</p></div> : <p className="manual-hint">Aceita youtube.com, youtu.be ou youtube-nocookie.com.</p>}<label>Prompt NotebookLM<textarea value={notebookPrompt} onChange={(event) => setNotebookPrompt(event.target.value)} placeholder="Cole o prompt personalizado desta aula" /></label><label>Roteiro do áudio<textarea value={audioScript} onChange={(event) => setAudioScript(event.target.value)} placeholder="Texto para o áudio complementar" /></label></div>}
    {step === 4 && <div className="manual-form"><h3>Questões e prompts</h3><label>Pergunta de revisão<textarea value={questionPrompt} onChange={(event) => setQuestionPrompt(event.target.value)} placeholder="Escreva uma questão autoral ou licenciada" /></label>{options.map((option, index) => <label key={index}>Alternativa {String.fromCharCode(65 + index)}{index === 0 ? " (gabarito)" : ""}<input value={option} onChange={(event) => setOptions((items) => items.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} /></label>)}<label>Explicação e fonte<textarea value={questionExplanation} onChange={(event) => setQuestionExplanation(event.target.value)} placeholder="Explique o gabarito e registre a fonte" /></label><p className="manual-hint">A questão só entra na trilha após conter alternativas, gabarito e fonte.</p></div>}
    {step === 5 && <div className="manual-preview"><h3>Revisão antes de liberar</h3><ul><li>{title && position && organization && city ? "Dados do concurso preenchidos" : "Complete título, cargo, órgão e cidade"}</li><li>{subjects.some((subject) => subject.title) ? "Há matéria para gerar módulo" : "Inclua pelo menos uma matéria"}</li><li>{videoId ? "Vídeo validado como URL do YouTube" : "Vídeo é opcional; mantenha PDF, áudio ou outro recurso"}</li><li>Liberação significa publicar apenas na sua área de estudo.</li></ul><p className="manual-hint">A liberação salva a trilha como pronta e mantém o concurso fora do catálogo oficial.</p></div>}
    {notice && <p className="manual-notice" role="status">{notice}</p>}<footer><button type="button" className="secundario" onClick={() => setStep((current) => Math.max(0, current - 1))} disabled={step === 0 || saving}>Voltar</button>{step < steps.length - 1 ? <button type="button" className="primario" disabled={!canAdvance || saving} onClick={advance}>{saving ? "Salvando" : "Continuar"}</button> : <button type="button" className="primario" disabled={!noticeId || saving} onClick={advance}>{saving ? "Liberando" : "Liberar para estudo"}</button>}</footer>
  </section>;
}
