"use client";

import { useState } from "react";

const materias = ["SUS e Saúde Coletiva", "Cariologia e Dentística", "Periodontia", "Português"];

export default function Home() {
  const [tela, setTela] = useState("entrada");
  const [aba, setAba] = useState("Resumo");
  const [respondeu, setRespondeu] = useState(false);
  const Header = () => <header><button className="marca" onClick={() => setTela("dashboard")}><b>O</b> OdontoTrack</button><nav><button onClick={() => setTela("dashboard")}>Editais</button><button onClick={() => setTela("trilha")}>Minha trilha</button><button>Biblioteca</button></nav><span className="avatar">RA</span></header>;
  if (tela === "entrada") return <main className="entrada"><section><span className="tag">ODONTOTRACK · CONCURSOS MUNICIPAIS</span><h1>Seu edital vira um plano de aprovação.</h1><p>Acompanhe São Paulo, Grande ABC e municípios próximos. Entenda o edital, estime o esforço e estude em uma trilha contínua.</p><button className="primario" onClick={() => setTela("dashboard")}>Entrar na minha área</button><small>Protótipo individual · dados demonstrativos</small></section><aside><span>PRÓXIMA AÇÃO</span><strong>Revisar Cariologia</strong><p>18 min · 7 questões</p><div className="progresso"><i style={{width:"42%"}} /></div></aside></main>;
  if (tela === "dashboard") return <><Header/><main className="pagina"><section className="intro"><div><span className="tag">OLÁ, RAFAEL</span><h1>Concursos compatíveis com você</h1><p>Atualizações verificadas hoje. Prioridade: Odontologia e ensino médio.</p></div><button className="secundario">Ajustar perfil</button></section><section className="grade"><article className="destaque"><span className="selo">ATUALIZADO HOJE</span><h2>Cirurgião-Dentista · Santo André</h2><p>Prefeitura Municipal · Ensino superior · 4 vagas</p><div className="fatos"><span><b>R$ 7.482</b>remuneração</span><span><b>20 out</b>prova prevista</span><span><b>12 set</b>fim das inscrições</span></div><button className="primario" onClick={() => setTela("edital")}>Analisar edital</button></article><article className="atualizacoes"><h3>Atualizações recentes</h3><p><b>Retificação</b><br/>Santo André: data da prova alterada</p><p><b>Novo edital</b><br/>ASB · São Bernardo do Campo</p><p><b>Em breve</b><br/>Odontologia · Guarulhos</p></article></section><h2>Decida antes de começar</h2><section className="passos"><article><b>1</b><h3>Analisar</h3><p>Resumo, requisitos, localização, etapas e mudanças da última versão.</p></article><article><b>2</b><h3>Estimar esforço</h3><p>Matérias, lacunas e carga semanal para avaliar a oportunidade.</p></article><article><b>3</b><h3>Criar curso</h3><p>Uma trilha individual com capítulos, materiais e revisões.</p></article></section></main></>;
  if (tela === "edital") return <><Header/><main className="pagina"><button className="voltar" onClick={() => setTela("dashboard")}>← Voltar aos editais</button><section className="intro"><div><span className="tag">EDITAL 01/2026 · VERSÃO 2</span><h1>Cirurgião-Dentista<br/>Santo André</h1><p>Prefeitura Municipal de Santo André · Instituto Mais</p></div><div className="fonte">✓ Fonte oficial<br/><small>atualizada há 2 horas</small></div></section><section className="grade"><article className="cartao"><h2>Visão geral do edital</h2><dl><dt>Inscrições</dt><dd>15 ago a 12 set 2026</dd><dt>Prova objetiva</dt><dd><mark>20 out 2026</mark> · alterada por retificação</dd><dt>Local de trabalho</dt><dd>Santo André · Grande ABC</dd><dt>Remuneração</dt><dd>R$ 7.482,00 · 30h semanais</dd></dl><a>Ver PDF oficial e histórico de versões ↗</a></article><article className="esforco"><span className="tag">DIAGNÓSTICO INICIAL</span><h2>106 a 132 horas</h2><p>Estimativa para cobrir o conteúdo programático, revisar e praticar.</p><div className="progresso"><i style={{width:"36%"}} /></div><small>8h/semana: 14 a 17 semanas</small><button className="primario" onClick={() => setTela("trilha")}>Criar minha trilha</button></article></section><section className="materias"><h2>Matérias do edital</h2>{materias.map((m,i)=><article key={m}><div><b>{m}</b><small>{i+4} capítulos · relevância alta</small></div><span>{i === 0 ? "100" : i === 1 ? "42" : "0"}%</span></article>)}</section></main></>;
  if (tela === "trilha") return <><Header/><main className="pagina"><button className="voltar" onClick={() => setTela("edital")}>← Voltar ao edital</button><section className="intro"><div><span className="tag">SUA TRILHA</span><h1>Cirurgião-Dentista<br/>Santo André</h1><p>36 tópicos · 23 capítulos · prova em 20 de outubro</p></div><div className="indice"><b>34%</b><br/>progresso geral<div className="progresso"><i style={{width:"34%"}} /></div></div></section><section className="trilha"><aside><h3>Conteúdo da trilha</h3>{materias.map((m,i)=><button className={i===1?"ativo":""} key={m} onClick={()=>i===1&&setTela("aula")}>{i===0?"✓":i+1} <span>{m}<small>{i+4} capítulos</small></span></button>)}</aside><article><span className="tag">CONTINUAR ESTUDOS</span><h2>Cariologia: diagnóstico, prevenção e tratamento</h2><p>Entenda fatores de risco, diagnóstico e condutas mais cobradas em concursos municipais.</p><p>◷ 48 min · ▣ vídeo + resumo · ◉ 10 questões</p><button className="primario" onClick={()=>setTela("aula")}>Continuar capítulo</button></article></section></main></>;
  return <><Header/><main className="pagina"><button className="voltar" onClick={() => setTela("trilha")}>← Voltar à trilha</button><section className="aula"><aside><span className="tag">ODONTOLOGIA · 2.2</span><h2>Cariologia</h2><p>Diagnóstico, prevenção e tratamento.</p><div className="progresso"><i style={{width:"42%"}} /></div>{materias.map(m=><button key={m}>{m}</button>)}</aside><article><span className="tag">CAPÍTULO 2 DE 6</span><h1>Cariologia: diagnóstico, prevenção e tratamento</h1><p>Objetivo: reconhecer fatores de risco, diagnóstico e condutas cobradas no edital.</p><div className="video">▶<small>Aula de professor parceiro · 28:00</small></div><nav className="abas">{["Resumo","PDF","Prompt IA","Questões","Áudio"].map(x=><button className={aba===x?"selecionada":""} onClick={()=>setAba(x)} key={x}>{x}</button>)}</nav>{aba==="Resumo"&&<section><h2>O que mais cai</h2><p>A doença cárie é multifatorial. Em provas municipais, atenção à interação entre biofilme, dieta fermentável, tempo e suscetibilidade do hospedeiro.</p><div className="nota"><b>Conexão com o edital</b><br/>Cariologia, diagnóstico e prevenção das doenças bucais.</div></section>}{aba==="PDF"&&<section><h2>Apostila OdontoTrack</h2><p>PDF autoral com seu layout próprio, versão e referência ao edital.</p><button className="secundario">Abrir material em PDF</button></section>}{aba==="Prompt IA"&&<section><h2>Estude com Gemini Notebook</h2><pre>Use apenas as fontes que eu adicionar. Explique Cariologia para o concurso de Cirurgião-Dentista de Santo André. Crie 10 questões e aguarde minhas respostas antes de corrigir.</pre><button className="primario" onClick={()=>navigator.clipboard?.writeText("Use apenas as fontes que eu adicionar. Explique Cariologia para o concurso de Cirurgião-Dentista de Santo André. Crie 10 questões e aguarde minhas respostas antes de corrigir.")}>Copiar prompt</button></section>}{aba==="Questões"&&<section><h2>Questão de consolidação</h2><p>Qual fator participa diretamente da desmineralização dental?</p><button className="resposta" onClick={()=>setRespondeu(true)}>A · Exposição frequente a carboidratos fermentáveis</button>{respondeu&&<div className="nota">✓ Correto. A frequência de exposição favorece quedas recorrentes do pH.</div>}</section>}{aba==="Áudio"&&<section><h2>Revisão em áudio</h2><p>Resumo narrado opcional para revisar onde estiver.</p><button className="secundario">▶ Ouvir agora · 08:12</button></section>}</article></section></main></>;
}
